import type { PlaceItem, TravelRouteOption, HotelRecommendation, RestaurantRecommendation } from '../src/types';

export interface DestinationPreset {
  id: string;
  name: string;
  state: string;
  tagline: string;
  tags: string[];
  bestSeason: string;
  nearbyFrom: Record<string, { distanceKm: number; routes: TravelRouteOption[] }>;
  whyDefault: string;
  places: PlaceItem[];
  hotels: HotelRecommendation[];
  restaurants: RestaurantRecommendation[];
  travelTips: string[];
}

export const DESTINATIONS_DB: Record<string, DestinationPreset> = {
  ooty: {
    id: 'ooty',
    name: 'Ooty (Udhagamandalam)',
    state: 'Tamil Nadu',
    tagline: 'Queen of Hill Stations surrounded by misty Nilgiri hills & tea estates',
    tags: ['Nature', 'Hill Station', 'Tea Plantations', 'Lakes', 'Viewpoints'],
    bestSeason: 'October to June',
    nearbyFrom: {
      coimbatore: {
        distanceKm: 86,
        routes: [
          { mode: 'TNSTC Bus (via Mettupalayam)', duration: '3 - 3.5 hrs', costEst: 140, details: 'Frequent buses from Coimbatore Gandhipuram Bus Stand directly up the Nilgiri Ghats.' },
          { mode: 'Nilgiri Mountain Toy Train', duration: '4.5 hrs', costEst: 205, details: 'UNESCO World Heritage steam rack train from Mettupalayam up to Ooty through 208 curves and tunnels.' },
          { mode: 'Shared Cab / Taxi', duration: '2.5 hrs', costEst: 1800, details: 'Comfortable private or shared cab along the scenic NH181 hairpin bends.' },
        ],
      },
      chennai: {
        distanceKm: 550,
        routes: [
          { mode: 'Overnight Nilgiri Express Train + Bus', duration: '9 hrs', costEst: 450, details: 'Overnight train from Chennai Central to Mettupalayam, then 1-hr bus/toy train to Ooty.' },
          { mode: 'AC Sleeper Bus', duration: '11 hrs', costEst: 850, details: 'Direct luxury sleeper buses departing Chennai in the evening.' },
        ],
      },
      bangalore: {
        distanceKm: 275,
        routes: [
          { mode: 'KSRTC Airavat Bus (via Bandipur)', duration: '6.5 hrs', costEst: 650, details: 'Scenic route passing through Bandipur and Mudumalai Tiger Reserves.' },
          { mode: 'Drive / Cab', duration: '5.5 hrs', costEst: 3500, details: 'Via Mysore and Bandipur Forest Ghat road.' },
        ],
      },
    },
    whyDefault: 'Ooty is within 86 km of Coimbatore, making it the most cost-effective and scenic nature getaway with lush tea gardens, pleasant climate, and affordable public transport.',
    places: [
      {
        id: 'ooty-lake',
        name: 'Ooty Lake & Boathouse',
        description: 'An iconic 65-acre artificial lake constructed in 1824, flanked by towering eucalyptus trees with pedal and row boating.',
        location: 'North Lake Road, Ooty',
        category: 'nature',
        thingsToDo: ['Pedal boating', 'Row boating', 'Cycling along perimeter', 'Mini-train ride for kids'],
        bestTimeToVisit: 'Morning 9:00 AM – 11:30 AM or 4:00 PM sunset',
        openingHours: '9:00 AM – 6:00 PM daily',
        entryFee: '₹13 per person (Boating ₹180 - ₹350)',
        entryFeeNumber: 13,
        nearbyAttractions: ['Deer Park', 'Thread Garden', 'Karnataka Siri Horticulture Garden'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2 hours',
        mapSearchQuery: 'Ooty Lake Tamil Nadu',
      },
      {
        id: 'botanical-garden',
        name: 'Government Botanical Garden',
        description: 'Sprawling 55-acre terraced garden established in 1848, featuring over 1,000 exotic species of flora, a 20-million-year-old fossilized tree trunk, and Italian style lawns.',
        location: 'Vannarapettai, Ooty',
        category: 'nature',
        thingsToDo: ['Walk the terraced lawns', 'Inspect 20M-year-old tree fossil', 'Fern house photography', 'Orchidarium tour'],
        bestTimeToVisit: '10:00 AM – 1:00 PM when blooms are brightly lit',
        openingHours: '7:00 AM – 6:30 PM daily',
        entryFee: '₹40 (Adults), ₹20 (Children)',
        entryFeeNumber: 40,
        nearbyAttractions: ['Toda Traditional Huts', 'Raj Bhavan gardens'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Government Botanical Garden Ooty',
      },
      {
        id: 'rose-garden',
        name: 'Government Rose Garden',
        description: 'Largest rose garden in India perched on the slopes of Elk Hill, showcasing over 20,000 varieties of roses in five curved terraces.',
        location: 'Elk Hill, Ooty',
        category: 'nature',
        thingsToDo: ['Marvel at miniature and hybrid tea roses', 'Panoramic view of Ooty town', 'Macro flower photography'],
        bestTimeToVisit: '3:00 PM – 5:30 PM for gentle lighting',
        openingHours: '8:30 AM – 6:00 PM daily',
        entryFee: '₹40 (Adults), ₹20 (Children)',
        entryFeeNumber: 40,
        nearbyAttractions: ['Elk Hill Murugan Temple', 'Charring Cross Market'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '1.5 hours',
        mapSearchQuery: 'Government Rose Garden Ooty',
      },
      {
        id: 'doddabetta-peak',
        name: 'Doddabetta Peak & Telescope House',
        description: 'The highest mountain in the Nilgiri Hills at 2,637 meters (8,650 ft). Offers breathtaking 360-degree vistas of misty valleys and the Western Ghats.',
        location: 'Ooty-Kotagiri Road (9 km from city center)',
        category: 'viewpoint',
        thingsToDo: ['View Bandipur forest canopy from Telescope House', 'Sip fresh Nilgiri spiced tea', 'Nature photography on ridge'],
        bestTimeToVisit: 'Early morning 8:30 AM before mist settles',
        openingHours: '9:00 AM – 6:00 PM daily',
        entryFee: '₹10 per adult (Telescope ₹10)',
        entryFeeNumber: 10,
        nearbyAttractions: ['Kotagiri tea valleys', 'Tea factory en-route'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2 hours',
        mapSearchQuery: 'Doddabetta Peak Ooty',
      },
      {
        id: 'tea-factory-museum',
        name: 'Doddabetta Tea Factory & The Tea Museum',
        description: 'Live working tea processing facility where visitors learn the CTC and orthodox manufacturing process from fresh leaf to finished brew.',
        location: 'Doddabetta Road, Ooty',
        category: 'culture',
        thingsToDo: ['Watch automated tea crush & drying rollers', 'Free freshly brewed cardamom tea tasting', 'Purchase handmade Nilgiri chocolates'],
        bestTimeToVisit: '11:00 AM – 2:00 PM',
        openingHours: '9:00 AM – 6:30 PM daily',
        entryFee: '₹30 for factory + ₹30 for chocolate museum',
        entryFeeNumber: 60,
        nearbyAttractions: ['Doddabetta summit', 'Eucalyptus oil distillery'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '1.5 hours',
        mapSearchQuery: 'Doddabetta Tea Factory Ooty',
      },
      {
        id: 'pykara-lake',
        name: 'Pykara Lake & Waterfalls',
        description: 'Pristine, non-commercial lake held sacred by the Toda community, nestled amidst dense shola forest with speed boating.',
        location: '21 km from Ooty on Mysore road',
        category: 'nature',
        thingsToDo: ['Speedboat ride on calm emerald waters', 'Short forest walk to Pykara waterfall cascades', 'Picnic by pine forest'],
        bestTimeToVisit: '11:00 AM – 3:30 PM',
        openingHours: '9:30 AM – 5:30 PM daily',
        entryFee: '₹10 entry (Boating extra ₹250 - ₹800)',
        entryFeeNumber: 10,
        nearbyAttractions: ['Shooting Point (Wenlock Downs 9th Mile)', 'Pine Forest'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Pykara Lake and Waterfalls Ooty',
      },
    ],
    hotels: [
      { name: 'Hotel Nilgiri Comforts / Youth Hostel', type: 'Budget', estPricePerNight: 750, currency: '₹', location: 'Near Commercial Road', rating: 4.1, amenities: ['Hot water', 'Free Wi-Fi', 'Travel Desk'], isEstimated: true },
      { name: 'Pine View Heritage Inn', type: 'Mid-Range', estPricePerNight: 1500, currency: '₹', location: 'Charing Cross', rating: 4.4, amenities: ['Mountain View', 'In-house Restaurant', 'Bonfire', 'Room Heater'], isEstimated: true },
      { name: 'Savoy - IHCL SeleQtions', type: 'Boutique', estPricePerNight: 6500, currency: '₹', location: 'Sylks Road', rating: 4.8, amenities: ['Heritage colonial fireplace', 'Fine dining', 'Spa'], isEstimated: true },
    ],
    restaurants: [
      { name: 'Junior Kuppanna Ooty', cuisine: 'Chettinad & South Indian', priceCategory: '₹₹', specialty: 'Biryani, mutton sukka, authentic parottas', location: 'Commercial Road' },
      { name: 'Hotel Annapoorna / Adyar Ananda Bhavan', cuisine: 'Pure Veg South Indian', priceCategory: '₹', specialty: 'Crispy Ghee Roast Dosa, Filter Coffee, Nilgiri Poori', location: 'ATC Junction' },
      { name: 'Earl’s Secret at Glass House', cuisine: 'Continental & Anglo-Indian', priceCategory: '₹₹₹', specialty: 'Roast chicken, shepherd’s pie, walnut pie', location: 'Havelock Road' },
    ],
    travelTips: [
      'Take government Nilgiri buses for local travel between Ooty, Coonoor, and Doddabetta to save up to 70% on local cabs.',
      'Purchase homemade chocolates directly around Commercial Road or the Botanical Garden gate for the freshest batch.',
      'Evenings drop down to 10°C–14°C year-round; carry at least one warm fleece or cardigan.',
      'Book Nilgiri Mountain Toy Train tickets in advance via IRCTC, or queue by 6:00 AM for unreserved general tickets.',
    ],
  },
  munnar: {
    id: 'munnar',
    name: 'Munnar',
    state: 'Kerala',
    tagline: 'Rolling emerald tea carpets, mist-draped valleys, and endangered Nilgiri Tahr',
    tags: ['Nature', 'Waterfalls', 'Wildlife', 'Tea Plantations'],
    bestSeason: 'September to May',
    nearbyFrom: {
      coimbatore: {
        distanceKm: 155,
        routes: [
          { mode: 'Direct KSRTC / SETC Bus', duration: '5.5 hrs', costEst: 260, details: 'Via Pollachi, Udumalpet and Marayoor sandalwood forest.' },
          { mode: 'Private Cab', duration: '4 hrs', costEst: 3200, details: 'Scenic Western Ghats drive via Chinnar Wildlife Sanctuary.' },
        ],
      },
      kochi: {
        distanceKm: 130,
        routes: [
          { mode: 'KSRTC Low Floor AC Bus', duration: '4 hrs', costEst: 220, details: 'Regular buses from Ernakulam KSRTC Stand to Munnar Town.' },
        ],
      },
    },
    whyDefault: 'Munnar offers world-renowned cascading tea valleys, cool highland breezes, and incredible biodiversity right across the border.',
    places: [
      {
        id: 'eravikulam-national-park',
        name: 'Eravikulam National Park (Rajamalai)',
        description: 'Home to the largest surviving wild population of the endangered Nilgiri Tahr and the rare Neelakurinji flowers that bloom once every 12 years.',
        location: 'Kannandevan Hills, Munnar',
        category: 'nature',
        thingsToDo: ['Spot wild Nilgiri Tahr goats', 'Safari bus up the mist clouds', 'Look up at Anamudi (South India’s highest peak)'],
        bestTimeToVisit: '8:30 AM – 11:00 AM',
        openingHours: '7:30 AM – 4:00 PM (Closed Feb-March for calving)',
        entryFee: '₹200 (Indian Adults), ₹150 (Children)',
        entryFeeNumber: 200,
        nearbyAttractions: ['Lakkam Waterfalls', 'Marayoor Sandalwood Forest'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '3 hours',
        mapSearchQuery: 'Eravikulam National Park Munnar',
      },
      {
        id: 'mattupetty-dam',
        name: 'Mattupetty Dam & Echo Point',
        description: 'A concrete gravity dam nestled between rolling tea gardens, famous for its calm reservoir, speedboats, and natural sound resonance at Echo Point.',
        location: 'Mattupetty, 13 km from Munnar',
        category: 'viewpoint',
        thingsToDo: ['Speedboat ride on reservoir', 'Test acoustic echo shouting', 'Stroll through eucalyptus stalls'],
        bestTimeToVisit: '11:00 AM – 2:00 PM',
        openingHours: '9:00 AM – 5:30 PM daily',
        entryFee: '₹20 entry per person',
        entryFeeNumber: 20,
        nearbyAttractions: ['Kundala Lake', 'Tea Gardens Photo Point'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Mattupetty Dam Munnar',
      },
      {
        id: 'tea-museum-munnar',
        name: 'KDHP Tea Museum (Tata Tea Museum)',
        description: 'Fascinating century-old museum demonstrating the evolution of tea manufacturing from 1905 roller machines to modern CTC tech.',
        location: 'Nullatanni Estate, Munnar',
        category: 'culture',
        thingsToDo: ['Watch tea processing demonstration', 'Tea tasting session', 'Documentary screening'],
        bestTimeToVisit: '2:30 PM – 4:30 PM',
        openingHours: '9:00 AM – 5:00 PM (Closed Mondays)',
        entryFee: '₹125 per person (Tea tasting ₹50)',
        entryFeeNumber: 125,
        nearbyAttractions: ['Pothamedu Viewpoint', 'Attukad Waterfalls'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '2 hours',
        mapSearchQuery: 'KDHP Tea Museum Munnar',
      },
    ],
    hotels: [
      { name: 'Munnar Backpackers Homestay', type: 'Budget', estPricePerNight: 800, currency: '₹', location: 'Old Munnar', rating: 4.2, amenities: ['Free Wi-Fi', 'Hot Shower', 'Valley Views'], isEstimated: true },
      { name: 'Misty Mountain Resort', type: 'Mid-Range', estPricePerNight: 1800, currency: '₹', location: 'Devikulam', rating: 4.5, amenities: ['Balcony View', 'Buffet Breakfast', 'Campfire'], isEstimated: true },
    ],
    restaurants: [
      { name: 'Rapsy Restaurant', cuisine: 'Kerala & Middle Eastern', priceCategory: '₹', specialty: 'Kerala Parotta, Beef Roast, Spanish Omelette', location: 'Main Bazaar' },
      { name: 'Saravana Bhavan Munnar', cuisine: 'South Indian Vegetarian', priceCategory: '₹', specialty: 'Thali meals, Ghee Roast, Fresh fruit juices', location: 'Munnar Town' },
    ],
    travelTips: [
      'Book Eravikulam National Park tickets online in advance to skip the 1-2 hour entry queue at the ticket counter.',
      'The route from Coimbatore via Chinnar Wildlife Sanctuary offers chances of spotting wild elephants and spotted deer in the early morning.',
    ],
  },
  wayanad: {
    id: 'wayanad',
    name: 'Wayanad',
    state: 'Kerala',
    tagline: 'Lush spice plantations, prehistoric caves, and mist-clad rainforest peaks',
    tags: ['Nature', 'Trekking', 'Waterfalls', 'Adventure', 'Caves'],
    bestSeason: 'October to May',
    nearbyFrom: {
      coimbatore: {
        distanceKm: 185,
        routes: [
          { mode: 'Train to Kozhikode + KSRTC Bus', duration: '5.5 hrs', costEst: 280, details: 'Train to Calicut (Kozhikode), then bus climbing Thamarassery Churam ghat.' },
          { mode: 'Direct Bus / Cab', duration: '5 hrs', costEst: 3500, details: 'Via Gudalur or Kozhikode.' },
        ],
      },
      bangalore: {
        distanceKm: 280,
        routes: [
          { mode: 'KSRTC Sleeper Bus', duration: '6 hrs', costEst: 550, details: 'Overnight route via Mysore and Sultan Bathery.' },
        ],
      },
    },
    whyDefault: 'Wayanad has dramatic waterfalls, bamboo forests, and ancient edakkal petroglyphs with high affordability.',
    places: [
      {
        id: 'banasura-sagar-dam',
        name: 'Banasura Sagar Dam',
        description: 'The largest earth dam in India and second largest in Asia, set against the backdrop of majestic Banasura peak with floating island views.',
        location: 'Padinjarathara, Wayanad',
        category: 'nature',
        thingsToDo: ['Speedboat ride between misty islands', 'Zip-lining over reservoir', 'Trek to Banasura peak base'],
        bestTimeToVisit: '9:00 AM – 11:30 AM',
        openingHours: '9:00 AM – 5:00 PM daily',
        entryFee: '₹40 per adult (Speedboat extra ₹800/boat)',
        entryFeeNumber: 40,
        nearbyAttractions: ['Karlad Lake', 'Meenmutty Waterfalls'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Banasura Sagar Dam Wayanad',
      },
      {
        id: 'edakkal-caves',
        name: 'Edakkal Caves',
        description: 'Prehistoric rock shelters on Ambukuthi Mala featuring Neolithic petroglyphs dating back to 6,000 BCE.',
        location: 'Nenmeni, Sultan Bathery',
        category: 'heritage',
        thingsToDo: ['Hike up 300+ stone steps', 'Observe Neolithic carvings of human figures & bows', 'Look out at three states convergence'],
        bestTimeToVisit: 'Morning 9:00 AM (Limited visitors allowed daily)',
        openingHours: '9:00 AM – 4:00 PM (Closed Mondays)',
        entryFee: '₹50 per adult',
        entryFeeNumber: 50,
        nearbyAttractions: ['Wayanad Heritage Museum', 'Phantom Rock'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Edakkal Caves Wayanad',
      },
      {
        id: 'soochipara-waterfalls',
        name: 'Soochipara (Sentinel Rock) Waterfalls',
        description: 'A spectacular 3-tiered waterfall cascading from 200 meters into a natural pool surrounded by dense deciduous forest.',
        location: 'Vellarimala, Meppadi',
        category: 'nature',
        thingsToDo: ['Walk down 1.5 km tea garden path', 'Dip feet in cool mountain stream', 'Rock climbing and forest photography'],
        bestTimeToVisit: '11:00 AM – 3:00 PM',
        openingHours: '9:00 AM – 5:00 PM daily',
        entryFee: '₹80 per person',
        entryFeeNumber: 80,
        nearbyAttractions: ['Chembra Peak', 'Kanthanpara Falls'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'Soochipara Waterfalls Wayanad',
      },
    ],
    hotels: [
      { name: 'Green Mount Bamboo Homestay', type: 'Budget', estPricePerNight: 900, currency: '₹', location: 'Kalpetta', rating: 4.3, amenities: ['Plantation Tour', 'Homemade Kerala Breakfast', 'Wi-Fi'], isEstimated: true },
      { name: 'Wayanad Silverwoods Nature Resort', type: 'Mid-Range', estPricePerNight: 2400, currency: '₹', location: 'Banasura Lake Road', rating: 4.6, amenities: ['Infinity Pool', 'Dam View', 'Spa'], isEstimated: true },
    ],
    restaurants: [
      { name: '1980’s A Nostalgic Restaurant', cuisine: 'Authentic Malabar Kerala', priceCategory: '₹₹', specialty: 'Banana leaf meals with fried fish, Malabar Biryani, Payasam', location: 'Kalpetta Bypass' },
      { name: 'Udupi Pure Veg', cuisine: 'South Indian Veg', priceCategory: '₹', specialty: 'Hot idlis, medu vada, filter coffee', location: 'Sultan Bathery' },
    ],
    travelTips: [
      'Edakkal Caves entry involves 300 stone steps; wear shoes with good grip.',
      'Check waterfall access during peak monsoon as entry is sometimes regulated for safety.',
    ],
  },
  pondicherry: {
    id: 'pondicherry',
    name: 'Puducherry (Pondicherry)',
    state: 'Puducherry',
    tagline: 'French colonial quarters, golden beaches, bohemian cafes, and spiritual tranquility',
    tags: ['Beach', 'Heritage', 'Culture', 'Food', 'Architecture'],
    bestSeason: 'October to March',
    nearbyFrom: {
      chennai: {
        distanceKm: 155,
        routes: [
          { mode: 'East Coast Road (ECR) Express Bus', duration: '3 hrs', costEst: 160, details: 'Scenic coastal highway buses departing CMBT & Thiruvanmiyur every 15 mins.' },
          { mode: 'Train to Puducherry Station', duration: '3.5 hrs', costEst: 110, details: 'Direct express passenger train.' },
        ],
      },
      coimbatore: {
        distanceKm: 380,
        routes: [
          { mode: 'Overnight Sleeper Bus', duration: '7.5 hrs', costEst: 550, details: 'Direct buses from Gandhipuram to Pondicherry New Bus Stand.' },
        ],
      },
    },
    whyDefault: 'Pondicherry combines charming French architecture, seaside promenade strolls, and affordable bicycle rentals.',
    places: [
      {
        id: 'promenade-beach',
        name: 'Promenade Beach & Rock Beach',
        description: 'A 1.5 km sea-facing boulevard closed to motorized vehicles every evening, lined with French colonial heritage buildings.',
        location: 'Goubert Avenue, White Town',
        category: 'beach',
        thingsToDo: ['Sunrise walk along the Bay of Bengal', 'Visit French War Memorial', 'Evening gelato stroll'],
        bestTimeToVisit: '5:30 AM sunrise or 5:00 PM sunset',
        openingHours: 'Open 24 hours (Vehicle-free 6 PM – 7:30 AM)',
        entryFee: 'Free',
        entryFeeNumber: 0,
        nearbyAttractions: ['Gandhi Statue', 'Old Light House', 'French Consulate'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Evening',
        approxDuration: '2 hours',
        mapSearchQuery: 'Promenade Beach Pondicherry',
      },
      {
        id: 'auroville-matrimandir',
        name: 'Auroville & Matrimandir Viewing Point',
        description: 'An international experimental township founded in 1968. The Matrimandir is a colossal golden sphere surrounded by 12 tranquil petals of silence.',
        location: 'Auroville, 10 km north of town',
        category: 'culture',
        thingsToDo: ['Walk shaded forest trail to Matrimandir viewing pavilion', 'Browse organic handmade boutiques', 'Solar Kitchen lunch'],
        bestTimeToVisit: '9:00 AM – 12:00 PM',
        openingHours: '9:00 AM – 5:00 PM (Visitor Centre)',
        entryFee: 'Free (Viewing Point pass free at Visitor Centre)',
        entryFeeNumber: 0,
        nearbyAttractions: ['Auroville Beach', 'Botanical Garden'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '3 hours',
        mapSearchQuery: 'Matrimandir Auroville',
      },
      {
        id: 'white-town-heritage',
        name: 'White Town (French Quarter) Heritage Walk',
        description: 'Vibrant yellow and pastel mustard-colored villas with bougainvillea draped over arched wooden gateways, bicycle-friendly streets, and art galleries.',
        location: 'White Town, Pondicherry',
        category: 'heritage',
        thingsToDo: ['Rent vintage bicycle (₹80/day)', 'Cafe hopping for croissants and French press', 'Visit Sri Aurobindo Ashram'],
        bestTimeToVisit: '3:30 PM – 6:30 PM',
        openingHours: 'Open all day',
        entryFee: 'Free',
        entryFeeNumber: 0,
        nearbyAttractions: ['Sri Aurobindo Ashram', 'Bharathi Park'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Afternoon',
        approxDuration: '2.5 hours',
        mapSearchQuery: 'White Town French Quarter Pondicherry',
      },
    ],
    hotels: [
      { name: 'Nomad House / Micasa Backpackers', type: 'Budget', estPricePerNight: 700, currency: '₹', location: 'Near Rock Beach', rating: 4.3, amenities: ['Free Wi-Fi', 'Bicycle Rental', 'Terrace Cafe'], isEstimated: true },
      { name: 'Villa Helena Heritage Hotel', type: 'Mid-Range', estPricePerNight: 1900, currency: '₹', location: 'White Town', rating: 4.6, amenities: ['French Courtyard', 'Air Conditioning', 'Free Breakfast'], isEstimated: true },
    ],
    restaurants: [
      { name: 'Cafe des Arts', cuisine: 'French & Continental', priceCategory: '₹₹', specialty: 'Nutella crepes, tartines, hibiscus iced tea', location: 'Suffren Street, White Town' },
      { name: 'Surguru Spot Pure Veg', cuisine: 'Traditional South Indian', priceCategory: '₹', specialty: 'Rava masala dosa, special thali, filter coffee', location: 'Sardar Vallabhai Patel Salai' },
    ],
    travelTips: [
      'Rent a bicycle or scooter (₹350/day) near the railway station to easily explore both White Town and Auroville.',
      'Goubert Avenue prohibits vehicles between 6 PM and 7:30 AM, making it a peaceful walker’s paradise.',
    ],
  },
  coorg: {
    id: 'coorg',
    name: 'Coorg (Kodagu)',
    state: 'Karnataka',
    tagline: 'Scotland of India with coffee blossom aromas, Abbey falls, and Tibetan monasteries',
    tags: ['Nature', 'Coffee', 'Waterfalls', 'Culture', 'Hill Station'],
    bestSeason: 'October to April',
    nearbyFrom: {
      bangalore: {
        distanceKm: 250,
        routes: [
          { mode: 'KSRTC Non-AC / Airavat Bus', duration: '5.5 hrs', costEst: 450, details: 'Direct buses from Satellite Bus Stand to Madikeri.' },
        ],
      },
      coimbatore: {
        distanceKm: 310,
        routes: [
          { mode: 'Train to Mysore + Bus to Madikeri', duration: '6.5 hrs', costEst: 320, details: 'Via Mysore and Kushalnagar.' },
        ],
      },
    },
    whyDefault: 'Coorg is famed for its lush coffee plantations, misty Raja’s Seat sunsets, and Namdroling Golden Temple.',
    places: [
      {
        id: 'abbey-falls',
        name: 'Abbey Falls',
        description: 'Tucked within private coffee plantations and spice estates, the Kaveri river cascades down a 70-foot cliff onto roaring boulders with a hanging bridge view.',
        location: 'Madikeri, Coorg',
        category: 'nature',
        thingsToDo: ['Walk down through coffee and black pepper vines', 'Photography on the suspension bridge', 'Taste fresh estate coffee'],
        bestTimeToVisit: '9:00 AM – 11:30 AM',
        openingHours: '9:00 AM – 5:00 PM daily',
        entryFee: '₹15 per person',
        entryFeeNumber: 15,
        nearbyAttractions: ['Madikeri Fort', 'Raja’s Tomb'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2 hours',
        mapSearchQuery: 'Abbey Falls Madikeri Coorg',
      },
      {
        id: 'rajas-seat',
        name: 'Raja’s Seat & Sunset Gardens',
        description: 'A seasonal garden of flowers and artificial fountains once favored by the Kings of Kodagu to watch sunsets overlooking mist-clad cliffs.',
        location: 'Madikeri Town',
        category: 'viewpoint',
        thingsToDo: ['Watch golden sunset over rolling Western Ghats ridges', 'Musical fountain show at 7 PM', 'Toy train joyride'],
        bestTimeToVisit: '4:30 PM – 6:45 PM for sunset',
        openingHours: '6:00 AM – 8:00 PM daily',
        entryFee: '₹5 entry (Fountain show ₹20)',
        entryFeeNumber: 5,
        nearbyAttractions: ['Madikeri Fort', 'Omkareshwara Temple'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Evening',
        approxDuration: '2 hours',
        mapSearchQuery: 'Rajas Seat Madikeri Coorg',
      },
      {
        id: 'namdroling-monastery',
        name: 'Namdroling Tibetan Monastery (Golden Temple)',
        description: 'The largest teaching center of Nyingma lineage of Tibetan Buddhism in the world, home to thousands of monks and 40-foot gold-plated Buddha statues.',
        location: 'Bylakuppe, Kushalnagar',
        category: 'culture',
        thingsToDo: ['Marvel at 40-foot gold statues of Buddha', 'Listen to peaceful monk chants and cymbals', 'Shop Tibetan handicrafts & momos'],
        bestTimeToVisit: '10:00 AM – 1:00 PM',
        openingHours: '9:00 AM – 6:00 PM daily',
        entryFee: 'Free',
        entryFeeNumber: 0,
        nearbyAttractions: ['Dubare Elephant Camp', 'Kaveri Nisargadhama'],
        liveOrEstimated: 'LIVE_VERIFIED',
        timeSlot: 'Morning',
        approxDuration: '2 hours',
        mapSearchQuery: 'Namdroling Monastery Golden Temple Bylakuppe',
      },
    ],
    hotels: [
      { name: 'Coffee Trail Estate Homestay', type: 'Homestay', estPricePerNight: 950, currency: '₹', location: 'Madikeri outskirts', rating: 4.4, amenities: ['Coffee plantation walk', 'Kodava dinner', 'Campfire'], isEstimated: true },
      { name: 'Heritage Resort Coorg', type: 'Mid-Range', estPricePerNight: 2300, currency: '₹', location: 'Galibeedu', rating: 4.5, amenities: ['Swimming Pool', 'Mountain view cottages', 'Ayurvedic Spa'], isEstimated: true },
    ],
    restaurants: [
      { name: 'Coorg Cuisine Restaurant', cuisine: 'Traditional Kodava & South Indian', priceCategory: '₹₹', specialty: 'Kadamputtu (rice dumplings), Pandi Curry, Bamboo shoot fry', location: 'Madikeri Main Road' },
      { name: 'Raintree Restaurant', cuisine: 'Multi-cuisine', priceCategory: '₹₹', specialty: 'Filter coffee, Coorg honey pancakes, chicken curry', location: 'Opposite Town Hall' },
    ],
    travelTips: [
      'Buy authentic Coorg spices (black pepper, cardamom, pure honey) directly from government-certified estate counters in Kushalnagar or Madikeri.',
    ],
  },
};

export const POPULAR_DESTINATIONS_LIST = [
  {
    id: 'ooty',
    name: 'Ooty (Udhagamandalam)',
    tagline: 'Misty Nilgiri hills, tea gardens & toy train',
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=600&q=80',
    startingFrom: 'Coimbatore, Chennai, Bangalore',
    idealDays: 2,
    budgetFrom: 4500,
    currency: '₹',
    tags: ['Nature', 'Hill Station', 'Tea', 'Budget-Friendly'],
    bestSeason: 'Oct – Jun',
  },
  {
    id: 'munnar',
    name: 'Munnar',
    tagline: 'Verdant green valleys, wildlife & cool waterfalls',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=600&q=80',
    startingFrom: 'Kochi, Coimbatore, Madurai',
    idealDays: 3,
    budgetFrom: 6000,
    currency: '₹',
    tags: ['Tea Gardens', 'Nature', 'Waterfalls'],
    bestSeason: 'Sep – May',
  },
  {
    id: 'wayanad',
    name: 'Wayanad',
    tagline: 'Rainforest treks, ancient caves & lakes',
    image: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?auto=format&fit=crop&w=600&q=80',
    startingFrom: 'Bangalore, Calicut, Coimbatore',
    idealDays: 3,
    budgetFrom: 5500,
    currency: '₹',
    tags: ['Nature', 'Adventure', 'Caves', 'Wildlife'],
    bestSeason: 'Oct – May',
  },
  {
    id: 'pondicherry',
    name: 'Pondicherry',
    tagline: 'French quarters, golden shores & cafe vibes',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=600&q=80',
    startingFrom: 'Chennai, Bangalore, Coimbatore',
    idealDays: 2,
    budgetFrom: 4000,
    currency: '₹',
    tags: ['Beach', 'Culture', 'French Quarter', 'Cafes'],
    bestSeason: 'Oct – Mar',
  },
  {
    id: 'coorg',
    name: 'Coorg',
    tagline: 'Coffee hills, Abbey cascades & monasteries',
    image: 'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=600&q=80',
    startingFrom: 'Bangalore, Mysore, Mangalore',
    idealDays: 2,
    budgetFrom: 5000,
    currency: '₹',
    tags: ['Coffee', 'Nature', 'Waterfalls'],
    bestSeason: 'Oct – Apr',
  },
];
