import React, { useState } from 'react';
import {
  MapPin,
  Calendar,
  Wallet,
  Users,
  Route,
  Bookmark,
  Printer,
  Share2,
  Check,
  Sparkles,
  BedDouble,
  Utensils,
  Lightbulb,
  ArrowRight,
  Info,
  Clock,
  Compass,
} from 'lucide-react';
import type { TripPlan } from '../types';
import { PlaceDetailCard } from './PlaceDetailCard';
import { BudgetPlannerCard } from './BudgetPlannerCard';
import { WeatherWidget } from './WeatherWidget';
import { LiveBadge } from './LiveBadge';

interface TripResultViewProps {
  tripPlan: TripPlan;
  onSaveTrip: (trip: TripPlan) => void;
  isSaved?: boolean;
  onNewPlan: () => void;
}

export const TripResultView: React.FC<TripResultViewProps> = ({
  tripPlan,
  onSaveTrip,
  isSaved = false,
  onNewPlan,
}) => {
  const [activeDay, setActiveDay] = useState(1);
  const [copied, setCopied] = useState(false);

  const currentDayData = tripPlan.itinerary.find((d) => d.dayNumber === activeDay) || tripPlan.itinerary[0];

  const handleShare = () => {
    const summary = `✈️ TourAI Itinerary: ${tripPlan.title}\n📍 Destination: ${tripPlan.destination} from ${tripPlan.startingPoint}\n💰 Budget: ${tripPlan.currency}${tripPlan.userBudget} (Est: ${tripPlan.currency}${tripPlan.budgetBreakdown.totalEstimated})\n⏳ Duration: ${tripPlan.durationDays} Days\n\nGenerated by TourAI – Smart Trip Planner`;
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div id="trip-result-view" className="w-full max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500 pb-16">
      {/* Top Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-white border border-slate-200/80 px-5 py-3 rounded-2xl shadow-sm print:hidden">
        <div className="flex items-center gap-2">
          <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
          <span className="text-xs font-semibold text-slate-700">AI Itinerary Ready</span>
          <span className="text-slate-300">|</span>
          <span className="text-xs text-slate-500">Starting from {tripPlan.startingPoint}</span>
        </div>

        <div className="flex items-center gap-2">
          <button
            id="save-trip-btn"
            onClick={() => onSaveTrip(tripPlan)}
            className={`inline-flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-xl border transition-all ${
              isSaved
                ? 'bg-emerald-50 text-emerald-700 border-emerald-200 shadow-xs'
                : 'bg-white hover:bg-slate-50 text-slate-700 border-slate-200'
            }`}
          >
            <Bookmark className={`w-3.5 h-3.5 ${isSaved ? 'fill-emerald-600 text-emerald-600' : ''}`} />
            <span>{isSaved ? 'Saved to My Trips' : 'Save Trip'}</span>
          </button>

          <button
            id="share-trip-btn"
            onClick={handleShare}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Share2 className="w-3.5 h-3.5" />}
            <span>{copied ? 'Summary Copied!' : 'Share'}</span>
          </button>

          <button
            id="print-trip-btn"
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-slate-700 transition-colors"
            title="Print or save as PDF"
          >
            <Printer className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Export / Print</span>
          </button>

          <button
            id="new-plan-btn"
            onClick={onNewPlan}
            className="inline-flex items-center gap-1.5 text-xs font-bold px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white transition-colors shadow-sm"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Plan Another</span>
          </button>
        </div>
      </div>

      {/* Hero Overview Banner */}
      <div className="bg-gradient-to-br from-emerald-900 via-slate-900 to-slate-900 text-white rounded-3xl p-6 sm:p-8 shadow-xl relative overflow-hidden">
        {/* Subtle decorative circles */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-1/3 w-64 h-64 bg-teal-500/10 rounded-full blur-2xl pointer-events-none" />

        <div className="relative z-10 max-w-4xl">
          <div className="flex flex-wrap items-center gap-2 mb-3">
            <span className="text-xs font-bold uppercase tracking-wider bg-emerald-500/20 text-emerald-300 border border-emerald-400/30 px-3 py-1 rounded-full">
              Recommended Destination
            </span>
            <span className="text-xs text-slate-300">
              {tripPlan.stateOrCountry} • Approx. {tripPlan.distanceKm} km from {tripPlan.startingPoint}
            </span>
          </div>

          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-white mb-3">
            {tripPlan.destination}
          </h1>

          {/* Quick Metrics Bar */}
          <div className="flex flex-wrap gap-4 sm:gap-6 text-xs sm:text-sm text-slate-200 mt-4 pt-4 border-t border-slate-700/60">
            <div className="flex items-center gap-2">
              <MapPin className="w-4 h-4 text-emerald-400" />
              <span><strong>From:</strong> {tripPlan.startingPoint}</span>
            </div>
            <div className="flex items-center gap-2">
              <Wallet className="w-4 h-4 text-emerald-400" />
              <span><strong>Budget:</strong> {tripPlan.currency}{tripPlan.userBudget.toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-emerald-400" />
              <span><strong>Duration:</strong> {tripPlan.durationDays} Days</span>
            </div>
            <div className="flex items-center gap-2">
              <Users className="w-4 h-4 text-emerald-400" />
              <span><strong>Travelers:</strong> {tripPlan.peopleCount} Person{tripPlan.peopleCount > 1 ? 's' : ''}</span>
            </div>
          </div>

          {/* Why Suggested Callout */}
          {tripPlan.whySuggested && (
            <div className="mt-5 bg-white/10 backdrop-blur-md rounded-2xl p-4 border border-white/15 text-xs sm:text-sm leading-relaxed text-slate-100 flex items-start gap-3">
              <div className="p-1.5 bg-emerald-500/30 rounded-lg text-emerald-300 mt-0.5 shrink-0">
                <Lightbulb className="w-4 h-4" />
              </div>
              <div>
                <span className="font-semibold text-emerald-300 block mb-0.5">Why TourAI Recommended {tripPlan.destination}:</span>
                <p>{tripPlan.whySuggested}</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Transit Routes & Travel Options */}
      {tripPlan.travelRoutes && tripPlan.travelRoutes.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-200/80 p-5 shadow-sm">
          <div className="flex items-center justify-between gap-2 mb-3">
            <div className="flex items-center gap-2">
              <div className="p-2 bg-blue-50 text-blue-600 rounded-xl">
                <Route className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 text-sm">Getting from {tripPlan.startingPoint} to {tripPlan.destination}</h3>
                <p className="text-xs text-slate-500">Distance: ~{tripPlan.distanceKm} km</p>
              </div>
            </div>
            <LiveBadge type="ESTIMATED" label="Estimated Routes" />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {tripPlan.travelRoutes.map((route, i) => (
              <div key={i} className="bg-slate-50 border border-slate-200/70 rounded-xl p-3.5 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between text-xs font-semibold text-slate-800 mb-1">
                    <span>{route.mode}</span>
                    <span className="text-emerald-700 font-bold">{tripPlan.currency}{route.costEst}</span>
                  </div>
                  <p className="text-[11px] text-slate-500 leading-relaxed">{route.details}</p>
                </div>
                <div className="mt-2 pt-2 border-t border-slate-200/60 flex items-center justify-between text-[11px] text-slate-400">
                  <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> Duration</span>
                  <span className="font-semibold text-slate-700">{route.duration}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Two Column Grid: Weather & Budget Planner */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <div className="lg:col-span-5">
          <WeatherWidget weather={tripPlan.weather} />
        </div>
        <div className="lg:col-span-7">
          <BudgetPlannerCard
            budget={tripPlan.budgetBreakdown}
            peopleCount={tripPlan.peopleCount}
            durationDays={tripPlan.durationDays}
          />
        </div>
      </div>

      {/* Day-by-Day Interactive Itinerary */}
      <div className="bg-white rounded-3xl border border-slate-200/80 p-6 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-4 mb-6 pb-4 border-b border-slate-100">
          <div>
            <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 tracking-tight">
              Day-by-Day Personalized Itinerary
            </h2>
            <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
              Sequenced for minimal transit fatigue and optimal daylight hours
            </p>
          </div>

          {/* Day Tabs */}
          <div className="flex items-center gap-1.5 p-1 bg-slate-100 rounded-2xl overflow-x-auto max-w-full">
            {tripPlan.itinerary.map((day) => (
              <button
                key={day.dayNumber}
                id={`day-tab-${day.dayNumber}`}
                onClick={() => setActiveDay(day.dayNumber)}
                className={`px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap ${
                  activeDay === day.dayNumber
                    ? 'bg-white text-emerald-800 shadow-xs'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Day {day.dayNumber}
              </button>
            ))}
          </div>
        </div>

        {/* Active Day Content */}
        {currentDayData && (
          <div className="space-y-6">
            {/* Day Header Banner */}
            <div className="bg-slate-50 border border-slate-200/80 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3">
              <div>
                <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-700 bg-emerald-100/60 px-2.5 py-0.5 rounded-full">
                  Day {currentDayData.dayNumber} Theme
                </span>
                <h3 className="text-base font-bold text-slate-900 mt-1">
                  {currentDayData.title}
                </h3>
                <p className="text-xs text-slate-500">{currentDayData.theme}</p>
              </div>

              {currentDayData.transportAdvice && (
                <div className="text-xs text-slate-600 max-w-md bg-white border border-slate-200/80 rounded-xl p-2.5 flex items-start gap-2">
                  <Info className="w-4 h-4 text-sky-500 shrink-0 mt-0.5" />
                  <span>{currentDayData.transportAdvice}</span>
                </div>
              )}
            </div>

            {/* Places Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {currentDayData.places.map((place, idx) => (
                <PlaceDetailCard key={place.id || idx} place={place} index={idx} />
              ))}
            </div>

            {/* Meal Recommendations for this Day */}
            {currentDayData.meals && (
              <div className="bg-amber-50/50 border border-amber-200/60 rounded-2xl p-4">
                <span className="text-xs font-bold uppercase tracking-wider text-amber-800 flex items-center gap-1.5 mb-2">
                  <Utensils className="w-4 h-4 text-amber-600" /> Curated Dining Schedule for Day {currentDayData.dayNumber}
                </span>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
                  {currentDayData.meals.breakfast && (
                    <div className="bg-white/80 p-2.5 rounded-xl border border-amber-100">
                      <span className="text-[10px] font-bold text-amber-800 block">Breakfast</span>
                      <p className="text-slate-700 mt-0.5">{currentDayData.meals.breakfast}</p>
                    </div>
                  )}
                  {currentDayData.meals.lunch && (
                    <div className="bg-white/80 p-2.5 rounded-xl border border-amber-100">
                      <span className="text-[10px] font-bold text-amber-800 block">Lunch</span>
                      <p className="text-slate-700 mt-0.5">{currentDayData.meals.lunch}</p>
                    </div>
                  )}
                  {currentDayData.meals.dinner && (
                    <div className="bg-white/80 p-2.5 rounded-xl border border-amber-100">
                      <span className="text-[10px] font-bold text-amber-800 block">Dinner</span>
                      <p className="text-slate-700 mt-0.5">{currentDayData.meals.dinner}</p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Accommodations & Dining Recommendations */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Hotels */}
        <div className="bg-white rounded-2xl border border-slate-200/80 p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <div className="p-2 bg-indigo-50 text-indigo-600 rounded-xl">
              <BedDouble className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-sm">Recommended Accommodations</h3>
              <p className="text-xs text-slate-500">Vetted by budget & reviews</p>
            </div>
          </div>

          <div className="space-y-3">
            {tripPlan.hotels.map((hotel, idx) => (
              <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-100 flex items-start justify-between gap-2">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-slate-900">{hotel.name}</span>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-slate-200/70 text-slate-700">
                      {hotel.type}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-500 mt-0.5 flex items-center gap-1">
                    <MapPin className="w-3 h-3 text-slate-400" /> {hotel.location} • ★ {hotel.rating}
                  </p>
                  <div className="flex flex-wrap gap-1 mt-1.5">
                    {hotel.amenities.map((am, i) => (
                      <span key={i} className="text-[10px] text-slate-600 bg-white px-1.5 py-0.5 rounded border border-slate-200/60">
                        {am}
                      </span>
                    ))}
                  </div>
                </div>
                <div className="text-right whitespace-nowrap">
                  <span className="text-xs font-extrabold text-slate-800">
                    {tripPlan.currency}{hotel.estPricePerNight}
                  </span>
                  <span className="text-[10px] text-slate-400 block">/ night</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Restaurants */}
        <div className="bg-white rounded-2xl border border-slate-200/80 p-5 shadow-sm">
          <div className="flex items-center gap-2 mb-4">
            <div className="p-2 bg-amber-50 text-amber-600 rounded-xl">
              <Utensils className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-sm">Local Authentic Dining</h3>
              <p className="text-xs text-slate-500">Regional flavors & popular eateries</p>
            </div>
          </div>

          <div className="space-y-3">
            {tripPlan.restaurants.map((rest, idx) => (
              <div key={idx} className="p-3 bg-slate-50 rounded-xl border border-slate-100 flex items-start justify-between gap-2">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-slate-900">{rest.name}</span>
                    <span className="text-[10px] font-semibold text-amber-700 bg-amber-100/70 px-1.5 py-0.5 rounded">
                      {rest.priceCategory}
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-500 mt-0.5">{rest.cuisine} • {rest.location}</p>
                  <p className="text-[11px] text-emerald-700 font-medium mt-1">Must Try: {rest.specialty}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Practical Travel Tips */}
      {tripPlan.travelTips && tripPlan.travelTips.length > 0 && (
        <div className="bg-slate-900 text-white rounded-3xl p-6 shadow-md">
          <div className="flex items-center gap-2.5 mb-4">
            <div className="p-2 bg-emerald-500/20 text-emerald-400 rounded-xl">
              <Compass className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-base">Essential Travel Tips & Advice for {tripPlan.destination}</h3>
              <p className="text-xs text-slate-400">Local customs, packing, and cost-saving insights</p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs leading-relaxed text-slate-300">
            {tripPlan.travelTips.map((tip, idx) => (
              <div key={idx} className="bg-white/5 border border-white/10 rounded-xl p-3 flex items-start gap-2.5">
                <span className="text-emerald-400 font-bold mt-0.5">•</span>
                <span>{tip}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
